# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

# trabalho/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          # 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      #- uses: actions/upload-artifact@v4
      - uses: dorny/test-reporter@v1 #ESSE AQUI È PRA EXIBIR O RELATORIO DIRETO NO SUMMARY DO GIT-ACTIONS
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: 'results.xml'
          reporter: jest-junit 
          #path: 'test-results/junit.xml' # Caminho padrão do arquivo JUnit XML gerado pelo Playwright
